"""change assignee table to have assigned by column

Revision ID: 94a58e11a945
Revises: c675e542c875
Create Date: 2026-10-08 10:33:21.168873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a58e11a945'
down_revision: Union[str, Sequence[str], None] = 'c675e542c875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignee', sa.Column('assigned_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignee', 'assigned_by')
    # ### end Alembic commands ###
